// RESUME BULLET: "Built AI Interview Question Generator using Groq LLaMA 3.3 70B
// that chains onto resume AI scores to generate 10 tailored technical, behavioral,
// and gap-based questions per candidate — with PDF export and email delivery"

import React, { useState, useEffect } from 'react';
import { formatDistanceToNow } from 'date-fns';
import { useGenerateQuestions, useGetQuestions, useDeleteQuestions, useEmailQuestions } from '../../hooks/useInterviewQuestions';
import { exportInterviewPDF } from '../../utils/exportInterviewPDF';

const loadingMessages = [
  "Analyzing job requirements...",
  "Reading candidate's skill profile...",
  "Crafting technical questions...",
  "Building behavioral questions...",
  "Targeting skill gaps...",
  "Finalizing your question set..."
];

export default function InterviewQuestionsPanel({ application, jobTitle }) {
  const { data: response, isLoading: isFetching } = useGetQuestions(application._id);
  const interviewData = response?.data;

  const generateMutation = useGenerateQuestions();
  const deleteMutation = useDeleteQuestions();
  const emailMutation = useEmailQuestions();

  const [activeTab, setActiveTab] = useState('All');
  const [expanded, setExpanded] = useState({});
  const [copiedIndex, setCopiedIndex] = useState({});
  const [copiedAll, setCopiedAll] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [emailStatus, setEmailStatus] = useState(null);

  const [msgIndex, setMsgIndex] = useState(0);
  const [dotIndex, setDotIndex] = useState(0);

  useEffect(() => {
    let msgTimer, dotTimer;
    if (generateMutation.isPending) {
      msgTimer = setInterval(() => {
        setMsgIndex((prev) => (prev + 1) % loadingMessages.length);
      }, 2000);
      dotTimer = setInterval(() => {
        setDotIndex((prev) => (prev + 1) % 3);
      }, 600);
    }
    return () => {
      clearInterval(msgTimer);
      clearInterval(dotTimer);
    };
  }, [generateMutation.isPending]);

  const handleGenerate = () => {
    generateMutation.mutate(application._id);
  };

  const handleDelete = () => {
    if (window.confirm("Delete these questions?")) {
      deleteMutation.mutate(application._id);
    }
  };

  const handleExportPDF = async () => {
    setIsExporting(true);
    const candidateName = application.candidate?.name || 'Candidate';
    try {
      exportInterviewPDF(interviewData, jobTitle, candidateName);
    } catch (err) {
      console.error(err);
    } finally {
      setTimeout(() => setIsExporting(false), 1500);
    }
  };

  const handleEmail = () => {
    setEmailStatus('sending');
    emailMutation.mutate(application._id, {
      onSuccess: () => {
        setEmailStatus('success');
        setTimeout(() => setEmailStatus(null), 2000);
      },
      onError: () => {
        setEmailStatus('error');
        setTimeout(() => setEmailStatus(null), 3000);
      }
    });
  };

  const questions = interviewData?.questions || [];

  const stats = {
    technical: questions.filter(q => q.category === 'technical').length,
    behavioral: questions.filter(q => q.category === 'behavioral').length,
    'gap-based': questions.filter(q => q.category === 'gap-based').length
  };

  const filteredQuestions = questions.filter(q => {
    if (activeTab === 'All') return true;
    return q.category.toLowerCase() === activeTab.toLowerCase();
  });

  const toggleExpand = (index) => {
    setExpanded(prev => ({ ...prev, [index]: !prev[index] }));
  };

  const copySingle = (e, q, index) => {
    e.stopPropagation();
    navigator.clipboard.writeText(q.question);
    setCopiedIndex(prev => ({ ...prev, [index]: true }));
    setTimeout(() => {
      setCopiedIndex(prev => ({ ...prev, [index]: false }));
    }, 1500);
  };

  const copyAll = () => {
    if (!questions.length) return;

    let text = `INTERVIEW QUESTIONS FOR: ${jobTitle}\nGenerated by AI Job Board\n\n`;

    const techQ = questions.filter(q => q.category === 'technical');
    if (techQ.length) {
      text += "TECHNICAL QUESTIONS:\n";
      techQ.forEach((q, i) => { text += `${i + 1}. ${q.question}\n`; });
      text += "\n";
    }

    const behQ = questions.filter(q => q.category === 'behavioral');
    if (behQ.length) {
      text += "BEHAVIORAL QUESTIONS:\n";
      behQ.forEach((q, i) => { text += `${techQ.length + i + 1}. ${q.question}\n`; });
      text += "\n";
    }

    const gapQ = questions.filter(q => q.category === 'gap-based');
    if (gapQ.length) {
      text += "GAP-BASED QUESTIONS:\n";
      gapQ.forEach((q, i) => { text += `${techQ.length + behQ.length + i + 1}. ${q.question}\n`; });
      text += "\n";
    }

    navigator.clipboard.writeText(text);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  };

  const getDifficultyColor = (diff) => {
    if (diff === 'easy') return 'bg-green-500/10 text-green-400 border border-green-500/20';
    if (diff === 'medium') return 'bg-amber-500/10 text-amber-400 border border-amber-500/20';
    return 'bg-red-500/10 text-red-400 border border-red-500/20';
  };

  const getCategoryColor = (cat) => {
    if (cat === 'technical') return 'bg-purple-muted text-purple-light border border-border-purple';
    if (cat === 'behavioral') return 'bg-blue-500/10 text-blue-400 border border-blue-500/20';
    return 'bg-amber-500/10 text-amber-400 border border-amber-500/20';
  };

  return (
    <div className="bg-bg-card border border-border-soft rounded-2xl overflow-hidden mt-4">
      {/* HEADER ROW */}
      <div className="flex justify-between items-center p-5 bg-bg-surface border-b border-border-soft">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-purple-light text-lg">⚡</span>
            <span className="text-text-primary font-bold text-base">AI Interview Questions</span>
          </div>
          <p className="text-text-hint text-xs mt-0.5 ml-7">Tailored for this candidate</p>
        </div>
        <div>
          {generateMutation.isPending ? (
            <button disabled className="bg-purple/50 text-white/50 rounded-xl px-4 py-2 text-sm font-bold flex items-center gap-2 cursor-not-allowed">
              <div className="w-4 h-4 rounded-full border-2 border-white/20 border-t-white animate-spin"></div>
              Generating...
            </button>
          ) : !interviewData ? (
            <button
              onClick={handleGenerate}
              className="bg-purple text-white rounded-xl px-4 py-2 text-sm font-bold hover:brightness-110 transition-all"
            >
              Generate Questions
            </button>
          ) : (
            <button
              onClick={handleGenerate}
              className="border border-purple/60 text-purple-light rounded-xl px-3 py-2 text-xs hover:bg-purple/10 transition-all flex items-center gap-2"
            >
              Regenerate
              {interviewData.regeneratedCount > 0 && (
                <span className="text-text-hint text-xs">(regenerated {interviewData.regeneratedCount} times)</span>
              )}
            </button>
          )}
        </div>
      </div>

      {/* LOADING STATE */}
      {generateMutation.isPending && (
        <div className="p-8 flex flex-col items-center justify-center gap-4 min-h-48">
          <div className="w-12 h-12 rounded-full border-2 border-bg-surface border-t-purple-light animate-spin"></div>
          <div className="text-text-muted text-sm text-center animate-pulse">
            {loadingMessages[msgIndex]}
          </div>
          <div className="flex gap-2 justify-center">
            {[0, 1, 2].map(i => (
              <div key={i} className={`w-2 h-2 rounded-full transition-all ${i === dotIndex ? 'bg-purple-light' : 'bg-bg-surface'}`}></div>
            ))}
          </div>
        </div>
      )}

      {/* EMPTY STATE */}
      {!generateMutation.isPending && !interviewData && (
        <div className="p-8 flex flex-col items-center justify-center gap-3 min-h-48">
          <div className="w-16 h-16 rounded-full bg-purple-muted border border-border-purple flex items-center justify-center mb-2">
            <span className="text-purple-light text-2xl">⚡</span>
          </div>
          <h3 className="text-text-primary font-bold text-base">No questions generated yet</h3>
          <p className="text-text-hint text-sm text-center max-w-xs leading-relaxed mb-4">
            Click Generate Questions to create AI-tailored interview questions based on this candidate's resume score and skill gaps
          </p>
          <div className="flex gap-2 flex-wrap justify-center mt-2">
            <span className="bg-purple-muted text-purple-light border border-border-purple rounded-full px-3 py-1 text-xs font-medium">
              Score: {application.aiScore || 0}/100
            </span>
            <span className="bg-green-500/10 text-green-400 border border-green-500/20 rounded-full px-3 py-1 text-xs font-medium">
              {application.aiSkillsMatched?.length || 0} matched
            </span>
            <span className="bg-red-500/10 text-red-400 border border-red-500/20 rounded-full px-3 py-1 text-xs font-medium">
              {application.aiSkillsMissing?.length || 0} gaps
            </span>
          </div>
        </div>
      )}

      {/* QUESTIONS VIEW */}
      {!generateMutation.isPending && interviewData && questions.length > 0 && (
        <>
          {/* STATS ROW */}
          <div className="grid grid-cols-3 gap-3 p-4 border-b border-border-soft">
            <div className="bg-bg-surface rounded-xl p-3 text-center">
              <div className="text-purple-light text-xl font-bold">{stats.technical}</div>
              <div className="text-text-hint text-xs">Technical</div>
            </div>
            <div className="bg-bg-surface rounded-xl p-3 text-center">
              <div className="text-blue-400 text-xl font-bold">{stats.behavioral}</div>
              <div className="text-text-hint text-xs">Behavioral</div>
            </div>
            <div className="bg-bg-surface rounded-xl p-3 text-center">
              <div className="text-amber-400 text-xl font-bold">{stats['gap-based']}</div>
              <div className="text-text-hint text-xs">Gap-based</div>
            </div>
          </div>

          {/* CATEGORY TABS */}
          <div className="flex gap-1 p-4 pb-0">
            {['All', 'Technical', 'Behavioral', 'Gap-based'].map(tab => {
              const isActive = activeTab === tab;
              const count = tab === 'All' ? questions.length : stats[tab.toLowerCase()];
              return (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`rounded-lg px-4 py-2 text-xs flex items-center transition-all ${isActive
                      ? 'bg-purple text-white font-bold'
                      : 'bg-bg-surface text-text-muted hover:bg-bg-card hover:text-text-primary'
                    }`}
                >
                  {tab}
                  <span className={`ml-1 rounded-full px-1.5 text-xs ${isActive ? 'bg-white/20' : 'bg-bg-card text-text-hint'}`}>
                    {count}
                  </span>
                </button>
              );
            })}
          </div>

          {/* QUESTIONS LIST */}
          <div className="p-4 space-y-3 max-h-[520px] overflow-y-auto">
            {filteredQuestions.map((q, filteredIndex) => {
              const originalIndex = questions.indexOf(q);
              const isExpanded = expanded[originalIndex];

              return (
                <div
                  key={originalIndex}
                  className="question-card bg-bg-surface border border-border-soft rounded-xl p-4 hover:border-purple/30 transition-all cursor-pointer group relative"
                  style={{ animationDelay: `${filteredIndex * 60}ms` }}
                  onClick={() => toggleExpand(originalIndex)}
                >
                  {copiedIndex[originalIndex] && (
                    <div className="absolute top-0 right-0 transform -translate-y-full mb-1 bg-bg-card border border-purple/40 text-purple-light text-xs px-2 py-1 rounded-lg z-10">
                      Copied!
                    </div>
                  )}

                  <div className="flex justify-between items-start gap-3">
                    <div className="flex items-start gap-3">
                      <div className="w-7 h-7 rounded-full bg-purple-muted border border-border-purple flex items-center justify-center text-purple-light text-xs font-bold flex-shrink-0">
                        {originalIndex + 1}
                      </div>
                      <p className="text-text-primary text-sm font-medium leading-relaxed mt-0.5">
                        {q.question}
                      </p>
                    </div>

                    <div className="flex gap-2 items-center flex-shrink-0">
                      <span className={`rounded-full px-2 py-1 text-xs font-medium capitalize ${getCategoryColor(q.category)}`}>
                        {q.category}
                      </span>
                      <span className={`rounded-full px-2 py-1 text-xs font-medium capitalize ${getDifficultyColor(q.difficulty)}`}>
                        {q.difficulty}
                      </span>
                      <button
                        className="opacity-0 group-hover:opacity-100 transition-opacity bg-bg-card border border-border-soft rounded-lg p-1.5 hover:border-purple/40 hover:text-purple-light"
                        onClick={(e) => copySingle(e, q, originalIndex)}
                        title="Copy question"
                      >
                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
                      </button>
                    </div>
                  </div>

                  {isExpanded && (
                    <div className="mt-3 pt-3 border-t border-border-soft space-y-2">
                      {q.purpose && (
                        <div>
                          <p className="text-text-hint text-xs font-medium uppercase tracking-wide">Why ask this?</p>
                          <div className="bg-purple-muted/50 rounded-lg p-3 mt-1 text-purple-light text-xs leading-relaxed italic">
                            💡 {q.purpose}
                          </div>
                        </div>
                      )}
                      {q.hint && (
                        <div className="mt-2">
                          <p className="text-text-hint text-xs font-medium uppercase tracking-wide">Strong answer looks like:</p>
                          <div className="bg-green-500/5 border border-green-500/10 rounded-lg p-3 mt-1 text-green-400 text-xs leading-relaxed">
                            ✓ {q.hint}
                          </div>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>

          {/* FOOTER ROW */}
          <div className="flex justify-between items-center p-4 border-t border-border-soft">
            <div className="flex items-center gap-2">
              <span className="text-text-hint text-xs">
                Generated {formatDistanceToNow(new Date(interviewData.generatedAt))} ago
              </span>
              {interviewData.regeneratedCount > 0 && (
                <span className="text-text-hint text-xs">
                  · Regenerated {interviewData.regeneratedCount}x
                </span>
              )}
            </div>

            <div className="flex gap-2 items-center relative">
              {copiedAll && (
                <span className="text-purple-light text-xs absolute -top-8 right-16">Copied!</span>
              )}
              <button
                onClick={copyAll}
                className="border border-border-soft text-text-muted rounded-lg px-3 py-1.5 text-xs hover:border-purple/40 hover:text-purple-light transition-all"
              >
                Copy All
              </button>
              
              <button
                onClick={handleExportPDF}
                disabled={isExporting}
                className="bg-purple text-white rounded-lg px-3 py-1.5 text-xs font-bold hover:brightness-110 transition-all flex items-center gap-1.5 ml-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isExporting ? 'Preparing PDF...' : (
                  <>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                      <polyline points="14 2 14 8 20 8"/>
                      <line x1="16" y1="13" x2="8" y2="13"/>
                      <line x1="16" y1="17" x2="8" y2="17"/>
                      <polyline points="10 9 9 9 8 9"/>
                    </svg>
                    Export PDF
                  </>
                )}
              </button>

              <div className="relative flex flex-col items-center">
                <button
                  onClick={handleEmail}
                  disabled={emailStatus === 'sending'}
                  className="border border-blue-500/40 text-blue-400 rounded-lg px-3 py-1.5 text-xs hover:bg-blue-500/10 transition-all flex items-center gap-1.5 ml-2 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {emailStatus === 'sending' ? 'Sending...' : emailStatus === 'success' ? (
                    <span className="text-green-400 flex items-center gap-1">✓ Sent!</span>
                  ) : (
                    <>
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
                        <polyline points="22,6 12,13 2,6"></polyline>
                      </svg>
                      Email Candidate
                    </>
                  )}
                </button>
                {emailStatus === 'error' && (
                  <span className="text-red-400 text-xs absolute -bottom-5 w-max">Failed to send</span>
                )}
              </div>

              <button
                onClick={handleDelete}
                className="text-text-hint text-xs hover:text-red-400 transition-colors ml-2"
              >
                Delete
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
